### ISSUE TITLE
07.22 스터디

### ISSUE THREAD

**Issue by jjuyeon** [jjuyeon/Tech-Interview-Study#18]
<h1>Network</h1>

- [x] IPv4, ICMP 프로토콜
- [x] 전송계층 및 포트
- [x] UDP 비연결지향형
- [x] TCP 연결지향형

**Comment by 483759** [comment]
TCP 연결지향형 프로토콜
------------------------
- TCP 프로토콜의 특징을 UDP 프로토콜과 비교하여 설명해주세요.
- 3-hand shaking에 대해 설명해주세요.

**Comment by shining8543** [comment]
UDP
- UDP 서버의 특징에 대해서 설명하세요.
- UDP는 어느 상황에서 사용하는지 설명하세요.

**Comment by jjuyeon** [comment]
## 전송계층, TCP 프로토콜
1. 3-way hand shaking에서 클라이언트가 서버가 보낸 ACK+SYC을 받지 못하면 어떻게 되나요?
2. 4-way hand shaking에서 서버가 마지막에 FIN을 보내는 이유는 무엇인가요?
3. 4-way hand shaking에서 클라이언트가 마지막에 ACK를 보내는 이유는 무엇인가요?
## 포트
1. Port란 무엇인가요?
2. 서버 측에서 사용되는 포트는 이미 정해져 있습니다. 주요 Well-Known Port에 대해 아는대로 설명해주세요.
3. 클라이언트와 서버의 통신 과정에 대해 설명해주세요.

**Comment by honggoii** [comment]
1. IPv4가 하는일과 IPv4 프로토콜 구조를 설명해주세요.
2. ICMP가 하는일과 ICMP 프로토콜 구조를 설명해주세요.
3. 다른 네트워크까지 내 패킷의 이동 과정을 설명해주세요.
